SHOP_DIENTHOAI/Controllers/DonHangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SHOP_DIENTHOAI.Models;

namespace SHOP_DIENTHOAI.Controllers
{
    public class DonHangController : Controller
    {
        ModelDienThoai dt = new ModelDienThoai();

        // Hiển thị danh sách đơn hàng
        public ActionResult Index()
        {
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("DangNhap", "User");
            }

            NGUOI_DUNG kh = (NGUOI_DUNG)Session["use"];
            int maND = kh.MA_ND;
            var donhangs = dt.DON_HANG.Include(d => d.NGUOI_DUNG).Where(d => d.MA_ND == maND);
            return View(donhangs.ToList());
        }

        // Xem chi tiết đơn hàng
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            DON_HANG donhang = dt.DON_HANG.Find(id);
            var chitiet = dt.CHI_TIET_DON_HANG.Include(d => d.SAN_PHAM).Where(d => d.MA_DON == id).ToList();

            if (donhang == null)
            {
                return HttpNotFound();
            }

            return View(chitiet);
        }

        // Xử lý hủy đơn hàng
        [HttpPost]
        public JsonResult CancelOrder(int id)
        {
            var order = dt.DON_HANG.Find(id);
            if (order == null)
            {
                return Json(new { success = false, message = "Đơn hàng không tồn tại!" });
            }

            // Kiểm tra điều kiện hủy đơn hàng
            if (order.TINH_TRANG != 0 || order.THANHTOAN != 1)
            {
                return Json(new { success = false, message = "Không thể hủy đơn hàng này!" });
            }

            // Xóa đơn hàng khỏi cơ sở dữ liệu
            dt.DON_HANG.Remove(order);
            dt.SaveChanges();

            return Json(new { success = true, message = "Đơn hàng đã được hủy thành công!" });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                dt.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SHOP_DIENTHOAI/Controllers/HangSanXuatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SHOP_DIENTHOAI.Models;

namespace SHOP_DIENTHOAI.Controllers
{
    public class HangSanXuatController : Controller
    {

        public ActionResult BrandList()
        {
            ModelDienThoai dt = new ModelDienThoai();
            List<HANG_SAN_XUAT> brs = dt.HANG_SAN_XUAT.ToList();
            return PartialView("BrandList", brs);
        }
        public ActionResult BrandProduct(int id, int page = 1, string sortBy = "")
        {
            ModelDienThoai dt = new ModelDienThoai();
            List<HANG_SAN_XUAT> brs = dt.HANG_SAN_XUAT.ToList();
            List<SAN_PHAM> sp = dt.SAN_PHAM.Where(row => row.MA_HSX == id).ToList();
            switch (sortBy)
            {
                case "Giá Bán tăng dần":
                    sp = sp.OrderBy(product => product.GIA).ToList();
                    break;
                case "Giá Bán giảm dần":
                    sp = sp.OrderByDescending(product => product.GIA).ToList();
                    break;
                case "Tên Sản Phẩm tăng dần":
                    sp = sp.OrderBy(row => row.TEN_SP).ToList();
                    break;
                case "Tên Sản Phẩm giảm dần":
                    sp = sp.OrderByDescending(row => row.TEN_SP).ToList();
                    break;
                default:
                    sp = sp.OrderBy(product => product.TEN_SP).ToList();
                    break;
            }
            //tìm sản phẩm trong các Hãng
            foreach (SAN_PHAM product in sp)
            {
                if (product.MA_SP == id)
                {
                    ViewBag.TenSanPham = product.HANG_SAN_XUAT.TEN_HSX;
                    break;
                }
            }
            //paging
            int NoOfRecordPage = 4;
            int NoOfPage = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(sp.Count) / Convert.ToDouble(NoOfRecordPage)));
            int NoOfRecordToSkip = (page - 1) * NoOfRecordPage;
            ViewBag.Page = page;
            ViewBag.NoOfPage = NoOfPage;
            sp = sp.Skip(NoOfRecordToSkip).Take(NoOfRecordPage).ToList();
      
            return View(sp);
        }
    }
}

SHOP_DIENTHOAI/Controllers/SanPhamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;
using SHOP_DIENTHOAI.Models;

namespace SHOP_DIENTHOAI.Controllers
{
    public class SanPhamController : Controller
    {
        // GET: SanPham
        public ActionResult Index(string search = "", string sortBy = "Sắp xếp theo", int page = 1)
        {
            ModelDienThoai dt = new ModelDienThoai();
            var products = dt.SAN_PHAM.Where(row => row.TEN_SP.Contains(search));
            if (search == null)
            {
                return HttpNotFound();
            }
            switch (sortBy)
            {
                case "Giá Bán tăng dần":
                    products = products.OrderBy(row => row.GIA);
                    break;
                case "Giá Bán giảm dần":
                    products = products.OrderByDescending(row => row.GIA);
                    break;
                case "Tên Sản Phẩm tăng dần":
                    products = products.OrderBy(row => row.TEN_SP);
                    break;
                case "Tên Sản Phẩm giảm dần":
                    products = products.OrderByDescending(row => row.TEN_SP);
                    break;
                default:
                    products = products.OrderBy(row => row.GIA);
                    break;
            }

            ViewBag.Search = search;
            ViewBag.SortBy = sortBy;
            int pageSize = 8; // Số sản phẩm trên mỗi trang
            int pageNumber = (page < 1) ? 1 : page; // Trang hiện tại

            // Sử dụng Skip và Take để phân trang sản phẩm
            var pagedProducts = products.Skip((pageNumber - 1) * pageSize).Take(pageSize).ToList();

            // Tính tổng số trang
            int totalProducts = products.Count();
            int totalPages = (int)Math.Ceiling((double)totalProducts / pageSize);

            // Pass thông tin phân trang qua ViewBag
            ViewBag.TotalPages = totalPages;
            ViewBag.CurrentPage = pageNumber;

            return View(pagedProducts);
        }
        public ActionResult ChiTiet(int id)
        {
            ModelDienThoai dt = new ModelDienThoai();
            var sp = dt.SAN_PHAM
                    .Include("COMMENT.NGUOI_DUNG")
                    .FirstOrDefault(row => row.MA_SP == id);
            if (sp != null)
            {
                return View(sp);
            }
            else
            {
                return HttpNotFound();
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken] // Bảo vệ chống tấn công CSRF
        public ActionResult ThemBinhLuan(int productId, string commentContent)
        {
            ModelDienThoai dt = new ModelDienThoai();

            if (Session["use"] == null)
            {
                TempData["ErrorMessage"] = "Bạn cần đăng nhập để bình luận!";
                return RedirectToAction("Dangnhap", "User");
            }

            if (string.IsNullOrWhiteSpace(commentContent))
            {
                TempData["ErrorMessage"] = "Bình luận không được để trống!";
                return RedirectToAction("ChiTiet", new { id = productId });
            }

            var kh = (NGUOI_DUNG)Session["use"];
            var comment = new COMMENT
            {
                NOIDUNG_CMT = commentContent,
                MA_SP = productId,
                MA_ND = kh.MA_ND,
                NGAY_CMT = DateTime.Now
            };

            dt.COMMENT.Add(comment);
            dt.SaveChanges();

            TempData["SuccessMessage"] = "Bình luận của bạn đã được đăng!";
            return RedirectToAction("ChiTiet", new { id = productId });
        }
        private ModelDienThoai dt = new ModelDienThoai();
        public List<SAN_PHAM> RandomSanPham(int soLuong)
        {
            return dt.SAN_PHAM.OrderBy(r => Guid.NewGuid()).Take(soLuong).ToList();
        }

        public ActionResult SanPhamTuongTu()
        {
            ModelDienThoai dt = new ModelDienThoai();
            var rdSP = RandomSanPham(3);
            return PartialView("SanPhamTuongTu", rdSP);
        }
    }

}

SHOP_DIENTHOAI/Views/Shared/_MainLayout.cshtml
@{
    ViewBag.Title = "_MainLayout";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>Shop Điện Thoại</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="~/Asset/css/bootstrap.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/Asset/css/style.css">


    <!-- Custom Fonts -->
    <link rel="stylesheet" href="~/Asset/font-awesome/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/Asset/fonts/font-slider.css" type="text/css">

    <!-- jQuery and Modernizr-->
    <script src="~/Asset/js/jquery-2.1.1.js"></script>

    <!-- Core JavaScript Files -->

    <script src="~/Asset/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body>
    @{ var u = Session["use"] as SHOP_DIENTHOAI.Models.NGUOI_DUNG; }
    <!--Top-->
    <nav id="top">
        <div class="container">
            <div class="row">
                <div class="col-xs-6">

                </div>  
                @{ if (u != null)
                    {
                        <div class="col-xs-6">
                            <ul class="top-link">
                                <li><a href="@Url.Action("HoSoNguoiDung", "User", new { id = u.MA_ND  })" style="color:orangered"><i class="fa-solid fa-user fa-beat-fade fa-sm" style="color: #0282e3;"></i> XIN CHÀO : <i class="fa-solid fa-address-card" style="color: #e4de1b;"></i> @u.TEN_ND</a></li>
                                <li><a href="/User/DangXuat"><i class="fa-solid fa-right-from-bracket fa-beat fa-sm" style="color: #ff1414;"></i> ĐĂNG XUẤT</a></li>
                            </ul>
                        </div>
                    }
                    else
                    {
                        <div class="col-xs-6">
                            <ul class="top-link">
                                <li><a href="/User/DangKy"><i class="fa-solid fa-user fa-beat-fade fa-sm" style="color: #0282e3;"></i> Đăng ký</a></li>
                                <li><a href="/User/DangNhap"><i class="fa-solid fa-right-from-bracket fa-beat fa-sm" style="color: #ff1414;"></i> Đăng nhập</a></li>      
                            </ul>
                        </div>
                    }
                }

            </div>
        </div>
    </nav>
    <!--Header-->
    <header class="container">
        <div class="row">
            <div class="col-md-4">
                <div id="logo"><a href="/Home/Index"><img src="~/Asset/images/LOGO.jpg" /></a></div>
            </div>
            <div class="col-md-4">
                <form class="form-search" action="/SanPham/Index">
                    <div class="input-group">
                        <input type="search"
                               class="input-medium search-query form-control"
                        id="search"
                        name="search"
                        placeholder="Tìm Kiếm" />

                        <span class="input-group-btn">
                            <button type="submit" class="btn">
                                <span class="glyphicon glyphicon-search"></span>
                            </button>
                        </span>
                    </div>
                </form>
            </div>


            <div class="col-md-4">
                @Html.Action("GioHangPartial", "GioHang", new { @class = "glyphicon" })
            </div>
        </div>
    </header>
    <!--Navigation-->
    <nav id="menu" class="navbar">
        <div class="container">
            <div class="navbar-header">
                <span id="heading" class="visible-xs">MENU</span>
                <button type="button" class="btn btn-navbar navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"><i class="fa fa-bars"></i></button>
            </div>
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">

                    <li>

                        @Html.ActionLink("Trang Chủ", "Index", "Home")
                    </li>
                    <li class="dropdown">
                        @Html.ActionLink("Sản phẩm", "Index", "SanPham")
                        @Html.Action("BrandList", "HangSanXuat")
                    </li>
                    <li>
                        @Html.ActionLink("Đơn Hàng", "Index", "DonHang")
                    </li>

                    <li><a href="https://www.facebook.com/lifeiiyu.14" target="_blank">Giới Thiệu</a></li>
                </ul>
            </div>
        </div>
    </nav>

    @RenderBody()
    <footer style="margin-top:45px">
        <div class="container">
            <div class="wrap-footer">
                <div class="row">
                    <div class="col-md-6 col-footer footer-1">
                        <img src="~/Asset/images/LOGO.jpg" />
                        <p>Đơn giản - Uy tín - Chất lượng</p>
                    </div>

                    <div class="col-md-6 col-footer footer-4">
                        <div class="heading"><h4>Liên lạc</h4></div>
                        <ul>
                            <li><span class="glyphicon glyphicon-home"></span>17 Nguyễn Hữu Tiến ,Tây Thạnh, Tân Phú,TP.HCM</li>
                            <li><span class="glyphicon glyphicon-earphone"></span>+84 379179281</li>
                            <li><span class="glyphicon glyphicon-envelope"></span>tn216003@gmail.com</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            <div class="container">
                <div class="row">
                    <div class="col-md-6">
                        Design by <a href="https://www.facebook.com/lifeiiyu.14">Nguyễn Công Tiến</a>
                    </div>
                    <div class="col-md-6">
                        <div class="pull-right">
                            <ul>
                                <li><img src="~/Asset/images/visa-curved-32px.png" /></li>
                                <li><img src="~/Asset/images/paypal-curved-32px.png" /></li>
                                <li><img src="~/Asset/images/discover-curved-32px.png" /></li>
                                <li><img src="~/Asset/images/maestro-curved-32px.png" /></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>